name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare CI config
      run: cp Makefiles/sledconf.ci ./sledconf
    - name: Build
      run: make
    - name: Test
      run: ./sled
  
  nspire:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sled

      - name: Checkout ndless
        uses: actions/checkout@v2
        with:
          repository: ndless-nspire/Ndless
          path: ndless
          submodules: 'recursive'
          fetch-depth: 0 # submodule checkout breaks with depth=1
      
      ## toolchain
      - uses: actions/cache@v2
        id: toolchain-cache
        with:
          path: ndless/ndless-sdk/toolchain/install
          # gcc/binutils/etc versions are in build_toolchain.sh
          key: ${{ runner.os }}-${{ hashFiles('ndless/ndless-sdk/toolchain/build_toolchain.sh') }}
      - name: Install ndless toolchain dependencies
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: sudo apt install -y libmpfr-dev libmpc-dev
      - name: Set up ndless toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        working-directory: ndless/ndless-sdk/toolchain
        run: ./build_toolchain.sh
      - name: Add toolchain to path
        run: echo "::add-path::$GITHUB_WORKSPACE/ndless/ndless-sdk/toolchain/install/bin"
      - name: Add SDK to path
        run: echo "::add-path::$GITHUB_WORKSPACE/ndless/ndless-sdk/bin"
      # ndless SDK
      - name: Install ndless SDK dependencies
        run: sudo apt install -y libboost-program-options-dev
      - name: Build ndless SDK
        run: make
        working-directory: ndless
      
      # actual build!
      - name: Prepare sledconf
        working-directory: sled
        run: |
          cp Makefiles/sledconf.ndless sledconf
          echo '::set-env name=NDLESS_SDK::../ndless/ndless-sdk'
          sed -i 's/DEFAULT_OUTMOD := ndless/DEFAULT_OUTMOD := dummy/' sledconf
      
      - name: Build sled
        working-directory: sled
