name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare CI config
      run: cp Makefiles/sledconf.ci ./sledconf
    - name: Build
      run: make
    - name: Test
      run: ./sled
  
  nspire:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout ndless toolchain
        uses: actions/checkout@v2
        with:
          repository: ndless-nspire/Ndless
          path: ndless
          submodules: 'recursive'
      - name: Set up ndless toolchain
        working-directory: ndless/ndless-sdk/toolchain
        run: ./build_toolchain.sh
